include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    missing_required_param: warning
    missing_return: warning
    sdk_version_async_exported_from_core: ignore
    implementation_imports: ignore
    invalid_annotation_target: ignore
    use_build_context_synchronously: false

  exclude:
    - "lib/generated/**"
    - "lib/**/*.g.dart"
    - "lib/**/*.config.dart"
    - "lib/**/*.freezed.dart"
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    always_put_control_body_on_new_line: true
    always_specify_types: true
    avoid_equals_and_hash_code_on_mutable_classes: false
    avoid_implementing_value_types: true
    depend_on_referenced_packages: true
    implicit_call_tearoffs: true
    lines_longer_than_80_chars: false
    no_default_cases: false
    omit_local_variable_types: false
    parameter_assignments: false
    prefer_foreach: true
    public_member_api_docs: false
    unnecessary_constructor_name: true
    unnecessary_lambdas: false
    unsafe_html: true
    use_colored_box: true
    use_decorated_box: true
    use_test_throws_matchers: true
