name: test_sas
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_redux: ^0.10.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  http: ^1.1.0
  injectable: ^2.3.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  provider: ^6.0.5
  redux: ^5.0.0
  redux_epics: ^0.15.1
  rxdart: ^0.27.7

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.3
  freezed: ^2.4.3
  injectable_generator: ^2.4.0
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0

flutter_intl:
  enabled: true
  arb_dir: assets/l10n

flutter:
  uses-material-design: true
