name: app - quality-assurance
on:
  push:

jobs:
  quality-assurance:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Setup project
        run: flutter pub get

      - name: Analyze flutter package
        run: dart analyze

      - name: Check format
        run: dart format -l 120 --set-exit-if-changed .